Merge mock-debug-extension with main
utdscheld/name pull request #11
Opened 2023-10-05 20:08 UTC by CowTipper989

Adding the first working iteration of the VSCode extension to main, as well as a readme.

2023-10-06 03:11 UTC, hkwheat approved these changes

2023-10-06 04:32 UTC, CharlesAverill requested changes

2023-10-06 04:32 UTC, CharlesAverill commented on .vscode/extensions.json
Is the `.vscode` directory necessary? I thought those were local configuration files

2023-10-06 04:32 UTC, CharlesAverill commented on CHANGELOG.md
Should go inside of a folder for the extension

2023-10-06 04:32 UTC, CharlesAverill commented on MyCheatsheet.md
This shouldn't be pushed to main, if you think it'll help with development later you can add it to the [wiki](https://github.com/utdscheld/name/wiki)

2023-10-06 04:32 UTC, CharlesAverill commented on ReadMe.md
Needs to go in a folder for the extension

2023-10-06 04:32 UTC, CharlesAverill commented on name-as/.artifacts/mips_test.out
Why was this removed?

2023-10-06 04:32 UTC, CharlesAverill commented on package.json
Needs to go in a folder for the extension

2023-10-06 04:48 UTC, CharlesAverill commented
After running `npm run watch` I'm stuck with this message and no debug window:
```
 *  Executing task: npm run watch 


> vsname@0.0.1 watch
> npm run -S esbuild-base -- --sourcemap --sources-content=false --watch


> vsname@0.0.1 esbuild-base
> esbuild ./src/extension.ts --bundle --tsconfig=./tsconfig.json --external:vscode --format=cjs --platform=node --outfile=dist/extension.js --sourcemap --sources-content=false --watch

[watch] build finished, watching for changes...
```

2023-10-09 19:47 UTC, CowTipper989 commented on .vscode/extensions.json
The .vscode directory is necessary. It defines the launch configuration for the extension, this is not something we will want to change per machine.

2023-10-09 19:48 UTC, CowTipper989 commented on .vscode/extensions.json
I had also thought they were just local configs before but when we didn't include them things got a little broken, upon looking into them more, yes they are important to keep lol

2023-10-09 20:07 UTC, CowTipper989 commented
> After running `npm run watch` I'm stuck with this message and no debug window:
> 
> ```
>  *  Executing task: npm run watch 
> 
> 
> > vsname@0.0.1 watch
> > npm run -S esbuild-base -- --sourcemap --sources-content=false --watch
> 
> 
> > vsname@0.0.1 esbuild-base
> > esbuild ./src/extension.ts --bundle --tsconfig=./tsconfig.json --external:vscode --format=cjs --platform=node --outfile=dist/extension.js --sourcemap --sources-content=false --watch
> 
> [watch] build finished, watching for changes...
> ```

This is intended behavior.

2023-10-09 21:12 UTC, CowTipper989 commented on MyCheatsheet.md
Good idea, done

2023-10-09 21:13 UTC, CowTipper989 commented on ReadMe.md
I will move the name extension to it's own folder

2023-10-09 21:13 UTC, CowTipper989 commented on CHANGELOG.md
I will move the name extension to it's own folder

2023-10-09 21:13 UTC, CowTipper989 commented on name-as/.artifacts/mips_test.out
I didn't realize it was important, I will readd it

2023-10-09 21:13 UTC, CowTipper989 commented on package.json
I will move the name extension to it's own folder

2023-10-09 21:14 UTC, CowTipper989 commented on MyCheatsheet.md
> +# Now for Svelte
It has been moved to a wiki page in the repo

2023-10-09 21:15 UTC, CowTipper989 commented
> Even when I started the extension debugger with F5 I had no extension running, is there any other way to start it up? @CowTipper989

Upon looking into this a little further, I believe their was an issue with the launch config in .vscode, I'll submit a new commit with a corrected launch.json and the other fixed before our meeting tonight

2023-10-09 21:33 UTC, CowTipper989 commented
The branch I am requesting to merge to main has been overhauled based on comments made earlier.
Please review again and alert me if anything else should be changed.

2023-10-09 22:45 UTC, CowTipper989 commented
Made a quick edit to remove merge conflicts with the gitignore and readme
- Added a full readme
- Changed gitignore to point to a folder within the sub directory of name-as since it has moved there

2023-10-10 00:17 UTC, qwe-q commented
NACK. This tampers with the git history by squashing changes. Let's merge from the branch where all the work was done

2023-10-10 00:17 UTC, closed without merging