Write formatter
utdscheld/name pull request #13
Opened 2023-10-06 06:41 UTC by CharlesAverill

@qwe-q and I currently disagree about whether or not this should be an independent extension. Putting up the PR now as a draft, will talk about it with John Cole tomorrow

2023-10-09 23:52 UTC, CowTipper989 requested changes
node_modules should be included in the .gitignore

2023-10-09 23:57 UTC, CharlesAverill commented
> node_modules should be included in the .gitignore

Fixed

2023-10-10 00:00 UTC, CowTipper989 commented
Looks good now

2023-10-10 00:03 UTC, CowTipper989 approved these changes

2023-10-16 22:45 UTC, qwe-q approved these changes

2023-10-16 22:46 UTC, hkwheat approved these changes

2023-10-16 22:49 UTC, merged